---
- name: Start Building Workstations
  hosts: all
  become: true
  gather_facts: true
  environment:
    GIT_SSL_NO_VERIFY: 1
    GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  roles:
    - kilip.workstation.build
