---
- name: Core tasks
  block:
    - name: Ensure deps task included
      ansible.builtin.include_tasks:
        file: deps/main.yml
        apply:
          tags: [deps]
      tags: [deps]

    - name: Ensure configure tasks included
      ansible.builtin.include_tasks: configure/main.yml
      tags: [configure]

  delegate_to: localhost
