---
- name: Core tasks
  block:
    - name: Ensure user tasks executed
      ansible.builtin.include_tasks:
        file: user/main.yml
        apply:
          tags: [deps]
    - name: Ensure deps tasks executed
      ansible.builtin.include_tasks:
        file: deps/main.yml
        apply:
          tags: [deps]
      tags: [deps]
      when: username != "linuxbrew"
  delegate_to: localhost
