---
- name: Ensure package facts are gathered
  ansible.builtin.package_facts:
    manager: auto

- name: Ensure sops stats gathered
  ansible.builtin.stat:
    path: "/usr/local/bin/sops"
  register: _sops

- name: Assert package installed
  ansible.builtin.assert:
    that: item in ansible_facts.packages
    quiet: true
    fail_msg: "package '{{ item }}' not installed"
  loop:
    - age
    - direnv

- name: Assert sops installed
  ansible.builtin.assert:
    that: _sops.stat.exists
    fail_msg: "sops not installed"
    quiet: true
