---
- name: Ensure cache updated
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 600

- name: Ensure required package installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - direnv
    - age

- name: Ensure sops stat gathered
  ansible.builtin.stat:
    path: "/usr/local/bin/sops"
  register: _sops

- name: Ensure mozilla sops installed
  block:
    - name: Ensure sops debian package downloaded
      ansible.builtin.get_url:
        url: https://github.com/mozilla/sops/releases/download/v3.7.3/sops_3.7.3_amd64.deb
        dest: "/tmp/sops.deb"
        validate_certs: false
    - name: Ensure sops installed
      ansible.builtin.apt:
        deb: /tmp/sops.deb
        state: present
  when: not _sops.stat.exists

- name: Ensure taskfile install status is checked
  ansible.builtin.command:
    cmd: "which task"
  changed_when: false
  failed_when: false
  register: _task

- name: Ensure taskfile installed
  block:
    - name: Ensure taskfile package download
      ansible.builtin.get_url:
        url: https://github.com/go-task/task/releases/download/v3.13.0/task_linux_amd64.deb
        dest: /tmp/task.deb
        validate_certs: false
    - name: Ensure taskfile installed
      ansible.builtin.apt:
        deb: /tmp/task.deb
        state: present
  when: _task.rc != 0
