---
dependency:
  name: galaxy
  options:
    role-file: ../../requirements.yml
    collection-file: ../../requirements.yml
driver:
  name: docker

platforms:
  - name: instance
    image: kilip/molecule-${DIST:-ubuntu-22.04}
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./:/workstation
    groups:
      - ${WS_TEST_GROUP:-workstations}

provisioner:
  name: ansible
  playbooks:
    converge: ../../playbook-main.yml
  inventory:
    links:
      group_vars: ../../inventory/group_vars
      host_vars: ../../inventory/host_vars
  config_options:
    defaults:
      vars_plugins_enabled: host_group_vars,community.sops.sops
verifier:
  name: ansible
