---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: kilip/molecule-ubuntu-22.04
    pre_build_image: true
    privileged: true

provisioner:
  name: ansible
  playbooks:
    converge: "${PROJECT_DIR}/build.yml"
  inventory:
    host_vars: "${PROJECT_DIR}/inventories/dev/host_vars"
    group_vars: "${PROJECT_DIR}/inventories/dev/group_vars"

verifier:
  name: ansible
