---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: kilip/molecule-${DIST:-ubuntu-22.04}
    pre_build_image: true
    privileged: true

provisioner:
  name: ansible
  playbooks:
    converge: "${PROJECT_DIR}/build.yml"
  inventory:
    links:
      group_vars: "${PROJECT_DIR}/inventories/${DEPLOY}/group_vars"

verifier:
  name: ansible
