---
dependency:
  name: galaxy
  options:
    role-file: ${PROJECT_DIR}/requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: kilip/molecule-${DIST:-ubuntu-22.04}
    pre_build_image: true
    privileged: true
    groups:
      - workstation
      - controlnode
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ${PROJECT_DIR}:/project

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${PROJECT_DIR}/roles
    SOPS_AGE_KEY_FILE: ${PROJECT_DIR}/molecule/default/age.keys
  playbooks:
    converge: "playbook-${PLAYBOOK:-build}.yml"
  inventory:
    links:
      group_vars: "${PROJECT_DIR}/molecule/default/group_vars"

verifier:
  name: ansible
