---
name: CI
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/ci.yml
      - inventory/**
      - molecule/default/**
    branches: [main]
  pull_request:
    paths:
      - .github/workflows/ci.yml
      - inventory/**
      - molecule/default/**
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3.
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: pip

      - name: Install test dependencies.
        run: pip3 install yamllint

      - name: Lint code.
        run: |
          yamllint .
  core:
    name: Integration ${{ matrix.group }}@${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: ubuntu-22.04
            group: servers
          - distro: ubuntu-22.04
            group: workstations
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip

      - name: Install test dependencies.
        run: make ansible-deps

      - name: Install mozilla sops
        uses: mdgreenwald/mozilla-sops-action@v1.2.0

      - name: Run Molecule tests.
        run: |
          make testing
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DIST: ${{ matrix.distro }}
          PROJECT_DIR: ${{ env.GITHUB_WORKSPACE}}
          WS_TEST_GROUP: ${{ matrix.group }}
