---
name: CI
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: 'kilip.workstation'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: kilip.workstation

      - name: Set up Python 3.
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: pip

      - name: Install test dependencies.
        run: pip3 install yamllint

      - name: Lint code.
        run: |
          yamllint .
  molecule:
    name: Molecule (${{ matrix.distro }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu-22.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: kilip.workstation

      - name: Set up python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip

      - name: Install test dependencies.
        run: make deps

      - name: Run Molecule tests.
        run: |
          make testing
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DIST: ${{ matrix.distro }}
          PROJECT_DIR: "/home/runner/work/workstation/workstation/kilip.workstation"
          DEPLOY: "dev"
          PLAYBOOK: deps
